#!/usr/bin/env python3.10

import argparse
import sys

from hash import rdf_hash, hash_methods


def parse_args(args=list[str]) -> argparse.Namespace:
    """Use argparse to parse list of arguments."""
    parser = argparse.ArgumentParser(
        description="Hash RDF blank nodes with sha256.",
    )

    parser.add_argument("-d", "--data", required=True, help="Input data. (RDF)")

    parser.add_argument(
        "-f",
        "--format",
        help="Input format.",
        default=None,
        choices=["turtle", "n-triples", "trig", "n-quads", "n3", "rdf"],
    )

    parser.add_argument(
        "-m",
        "--method",
        help="Hash method.",
        default="sha256",
        choices=hash_methods.keys(),
    )

    parser.add_argument(
        "-a",
        "--accept",
        help="Accept format.",
        default=["turtle"],
        nargs="+",
    )

    return parser.parse_args(args)


if __name__ == "__main__":
    args = parse_args(sys.argv[1:])
    graph = rdf_hash(args.data, args.format, args.method)
    print(graph.serialize(format=args.accept[0]))
